USE [master]
GO
IF NOT EXISTS(select * from sys.databases where name = '$(DATABASE_NAME)')
Begin
CREATE DATABASE [$(DATABASE_NAME)] ON (
  NAME = N'$(DATABASE_NAME)_Data', 
  FILENAME = N'$(DATABASE_PATH_PRIMARY)\$(DATABASE_NAME)_Data.MDF' , 
  SIZE = 3MB, 
  MAXSIZE = UNLIMITED,
  FILEGROWTH = 5MB) 
 LOG ON (
  NAME = N'$(DATABASE_NAME)_Log', 
  FILENAME = N'$(DATABASE_PATH_LOG)\$(DATABASE_NAME)_Log.LDF' , 
  MAXSIZE = UNLIMITED,
  SIZE = 576KB, 
  FILEGROWTH = 2MB)
end
GO